name = "DavidsMath"
version = "0.1.0"
keywords = ["math"]
leanOptions = []

[[lean_lib]]
name = "DavidsMath"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"
